### ISSUE TITLE
Establish initial structure and scope of tabler

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/tabler#2]
# Overview
The goal is essentially to create a function that makes it quick and easy to create summary/descriptive tables. At this point, I'm still trying to figure out what I want the structure and scope of the package to look like. 

## 2024-02-29 Update
* I was looking through the [gt package documentation](https://gt.rstudio.com/) last night. At first, I was concerned that tabler would be redundant with the gt package. I don't think it would be. The gt package is about making nicely formatted tables from an existing data frame. The tabler package is supposed to help transition raw data into a data frame of summary statistics that can then be made nicely formatted by another package (e.g., gt or flextable). So, I don't think the objectives are overlapping. However...
* Maybe tables are too complicated to easily reduce the process down to a couple of functions.
* Perhaps it's best if I just use this repo for some example vignettes to walk me through the process of making summary tables. 
* Perhaps this repo can have some helper functions as well. 
* Remember, the most important goal is to make it useful to YOU.
* Also, it can expand over time.

## Some initial thoughts on how I want it to work
* tabler doesn’t **do** any analysis. It’s just a framework for applying your analysis in an organized way and formatting the results for dissemination.
* Don’t worry about compatibility with freq tables and mean tables. Just think I’m terms of base R and summarize.
* Start with making tabler about helper functions. That way, it can be helpful in situations I’ve never imagined.
* Make separate functions for descriptive tables and regression tables?
* Diagram what the output needs to look like. Analysis variables in the rows. Group variable(s) in the columns. One group at a time. Stats formatted as characters.

## One possible structure
* `tabler_rows()`. This is where we input information about which variables we want to use and what statistical operations we want to perform on them.
* `tabler_columns()`. This is where we input information about what groups we want to compare. There should also be a special convenience function for overall.
* `tabler()`. This builds the final table as a data frame.
* Next, we will typically pass the built table to flextable, but we don't have to.
* Create some helper functions that take care of common formatting tasks.

## Scenarios
You may use these, you may not
- [ ] Include all variables in the data frame - only one summary function.
- [ ] Include a subset of variables from the data frame - only one summary function.
- [ ] Divide all variables into either categorical or continuous - one summary function for each.
- [ ] Set a different function for each variable.
- [ ] Create summary tables with multiple grouping variables - an overall column.

## Left off at
Just experimenting a figuring out how I want things to work in experimenting.qmd

## Task list
- [x] Create an example data frame.
- [ ] Figure out the basic structure and scope of `tabler`
- [ ] Create a basic "how to" README
- [ ] Initial checks
- [ ] Commit and push
